import asyncio

from ragbench.app.generation.base import GenerationResult, LLMProvider


class MockLLMProvider(LLMProvider):
    def __init__(self, delay_ms: int = 500) -> None:
        self.delay_ms = delay_ms

    async def generate(self, prompt: str, *, system_prompt: str) -> GenerationResult:
        await asyncio.sleep(self.delay_ms / 1000.0)

        # Make a mock answer
        answer = (
            "Based on the retrieved context, this is a simulated response generated by the "
            "MockLLMProvider. It successfully assembled the context from Qdrant into a prompt "
            "and executed the generation step."
        )

        return GenerationResult(
            text=answer,
            model="mock-llm",
            input_tokens=150,
            output_tokens=50,
        )
